### ISSUE TITLE
can't loading module

### ISSUE THREAD

**Issue by p1k0pan** [ixru/nvim-markdown#1]
when I wanna use `control-k` or `control-c` , it shows the following errors.
![2021-10-08-1633666155_1505x55](https://user-images.githubusercontent.com/36180022/136497645-afbc3b4d-e421-45aa-b424-3eded5819621.jpg)
![2021-10-08-1633666208_1041x64](https://user-images.githubusercontent.com/36180022/136497649-526ec297-ecf7-4a04-a9e9-53bea89fc8bd.jpg)

**Comment by ixru** [comment]
The topmost error comes from neovim changing a function name in the nightly version. I thought only I used this, but I will change it back so it works with the release version again. I'm not sure about the second message, but I guess it's related. Just post here if it persists after I change it.

**Comment by ixru** [comment]
It looks like it was changed to on_key in the newest release, so you should just update your neovim to have it working.

**Comment by p1k0pan** [comment]
ok control-c seems work out in list. But `tab` still pop out this error
![2021-10-11-1633966813_1688x59](https://user-images.githubusercontent.com/36180022/136818373-4fe51c68-3bed-4e98-8222-b9325c4cc4d1.jpg)

**Comment by ixru** [comment]
Fixed now I think.

**Comment by p1k0pan** [comment]
> Fixed now I think.

yes

**Comment by p1k0pan** [comment]
and `:InsertToc` can't show h1
![2021-10-12-1634011683_334x318](https://user-images.githubusercontent.com/36180022/136890610-7d09bad3-47b7-4074-a37d-d13c2310e129.jpg)

Also use `return` to open a link(github)  get some error, but ok with open local file(myfile)
![2021-10-12-1634012351_761x213](https://user-images.githubusercontent.com/36180022/136890820-52bb2108-4fc0-4210-a0a9-6a9071aa8ed2.jpg)

**Comment by p1k0pan** [comment]
Also I want to make some another suggestion. 
1. The preview effect is perfect. But typing a link address is invisible, and don't know where is the parentheses to input the address
2. `Toc` is awesome. May be you can make every title in different color to be prettier and better recognizing the structure.
3. May be is better that closing the split windows after the user click `return` and jump to the title

**Comment by ixru** [comment]
For problem 1, it looks like inserttoc was implemented assuming that h1 is the title of the document, so only sub-headers should be included in the toc. I don't really know if it's better to include h1's. If you don't think this explanation makes sense maybe it should be changed. edit: [style guide](https://google.github.io/styleguide/docguide/style.html#document-layout) says h1 is title, so it should probably stay as it is.

For problem 2, I'm not sure what's wrong. You're supposed to have netrw enabled by default. What happens if you try to open a folder? `nvim ~` for example if you're on linux. Might also be that running Windows is the problem. 

I took a look at the nvim config you have on github, and it looks like you have `concealcursor` enabled in insert mode. If you remove it, it will show the link when you have the cursor on the link's line. This is usually a concious choice by the user I believe, so I chose not to interfere.

It's too hard to do syntax stuff without Treesitter, and markdown hasn't been merged into nvim-treesitter yet.

I don't know what you mean by split. There aren't supposed to be any. I found an error when jumping to anchors and will update that, but I need more info to know what you mean.

**Comment by ixru** [comment]
How did you find this plugin by the way?

**Comment by p1k0pan** [comment]
1. yes that make sense  to me.  
2. `nvim ~` will just start a file to edit but can't save. 
3. `concealcursor` is actually the problem, I will change it.
4. about colorizing structure, left is the plugin `dooutline`  , and the right is `Toc`. I think just make them some color hhhhh
![2021-10-12-1634042986_1920x1049](https://user-images.githubusercontent.com/36180022/136959650-8e6b1676-545b-488e-b900-e15aa3831833.jpg)
5. Splitting window is when I type `Toc` it splits out a window on right and shows the contents (in the screenshot right). When I press `enter` to jump to a header, that window is still here and I have to close it manually.

**Comment by p1k0pan** [comment]
> How did you find this plugin by the way?

I want a plugin that can generate toc and find it, and I found your extension is quite good

**Comment by ixru** [comment]
Your [config](https://github.com/p1k0pan/nvimdotfile/blob/master/lua/core/init.lua#L38) says netrw is disabled, so it's probably that.
I like the color idea, I'll see what I can do. 
I think the split should stay open. It's meant to be used several times after all, so you don't have to rerun the command each time you want to jump. I was thinking maybe just keeping the cursor in the split when jumping, since it's used more as a way to get an overview when used for markdown.

**Comment by p1k0pan** [comment]
even I enable netrw it is still not working with that error :(

**Comment by ixru** [comment]
You enabled the 3 lines below where I linked too?

**Comment by p1k0pan** [comment]
> You enabled the 3 lines below where I linked too?
yes

**Comment by ixru** [comment]
Well, then you'll have to debug why netrw isn't loaded yourself. Try with `nvim -u NORC`. It can be launched with `:Explore` too, I found.
