### ISSUE TITLE
Implement "go to edit" mapping 'ge' as in original vim plugin

### ISSUE THREAD

**Issue by voyeg3r** [ixru/nvim-markdown#3]
It would be great to also have this feature.

In the original: vim-markdown when you have a word under cursor and press 'ge' vim will create a new file under that name.

**Comment by ixru** [comment]
Sorry, I don't get notifications for some reason.

I made both 'gx' and 'ge' be 'Return' instead because I liked it better. Looking at it though I think it would be a good idea to make it create links too instead of 'C-k' in normal mode, since many use that for moving between windows.

You can remap to 'ge' if you want with: 'map ge \<Plug>Markdown_FollowLink'
